version: '3'
services:
  webapp:
    container_name: empapi
    build: .
    ports:
      - "5000:5000"
    environment:
     - NODE_ENV=Production
     - MONGOURI=mongodb://167.71.239.50:27017
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /root/Mongodbdata:/data/db
  mongoexpress:
    image: mongo-express
    container_name: mongoadmin
    restart: always
    ports:
      - '8083:8081'
    depends_on:
      - mongo      
