version: '3'
services:
  weba:
    container_name: nodeapp
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
